<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.3.25171.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="..\Birko.Models\Birko.Models.projitems" Label="Shared" />
  <Import Project="..\Birko.Data.Core\Birko.Data.Core.projitems" Label="Shared" />
  <Import Project="..\Birko.Data.Stores\Birko.Data.Stores.projitems" Label="Shared" />
  <Import Project="..\Birko.MessageQueue\Birko.MessageQueue.projitems" Label="Shared" />
  <Import Project="..\Birko.MessageQueue.InMemory\Birko.MessageQueue.InMemory.projitems" Label="Shared" />
  <Import Project="..\Birko.MessageQueue.MQTT\Birko.MessageQueue.MQTT.projitems" Label="Shared" />

</Project>
